// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TailwindCSSIntellisense
{
    internal sealed partial class Vsix
    {
        public const string Id = "TailwindCSSIntellisense.b29696d4-76a4-43d1-a203-c8e692368847";
        public const string Name = "Tailwind CSS for Visual Studio";
        public const string Description = @"Unofficial extension for Tailwind CSS IntelliSense, linting, sorting, and more in Visual Studio 2026 and 2022.";
        public const string Language = "en-US";
        public const string Version = "1.13.4.1";
        public const string Author = "Theron Wang";
        public const string Tags = "tailwind, tailwind css, css, html, cshtml, razor, blazor, intellisense, auto-completion";
        public const bool IsPreview = false;
    }
}
