// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TailwindCSSIntellisense
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSPackageString = "615fb6c4-7ae7-4ae8-b3ec-271ea26d9481";
        public static Guid guidVSPackage = new Guid(guidVSPackageString);

        public const string guidWorkspaceExplorerToolWindowCmdSetString = "cfb400f1-5c60-4f3c-856e-180d28def0b7";
        public static Guid guidWorkspaceExplorerToolWindowCmdSet = new Guid(guidWorkspaceExplorerToolWindowCmdSetString);

        public const string guidVSPackageCmdSetString = "0da954de-3d1d-4742-b780-37f890b19009";
        public static Guid guidVSPackageCmdSet = new Guid(guidVSPackageCmdSetString);

        public const string guidImagesString = "2320d8cb-5f2f-4c20-af58-1877e2b1d14a";
        public static Guid guidImages = new Guid(guidImagesString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int idmWSE_ContextMenu = 0x0002;
        public const int WorkspaceMenuGroup = 0x1010;
        public const int MenuGroup = 0x1020;
        public const int BuildMenuGroup = 0x1030;
        public const int ProjMenuGroup = 0x1040;
        public const int ToolsMenuGroup = 0x1050;
        public const int OutputMenuGroup = 0x1060;
        public const int SetupMenuGroup = 0x1070;
        public const int SetAsConfigFileCmdId = 0x0100;
        public const int SetAsCssFileCmdId = 0x0101;
        public const int RemoveAsConfigFileCmdId = 0x0103;
        public const int RemoveAsCssFileCmdId = 0x0104;
        public const int RemoveAsOutputCssFileCmdId = 0x0105;
        public const int StartBuildProcessCmdId = 0x0106;
        public const int StartMinifyBuildProcessCmdId = 0x0107;
        public const int StartUnminifyBuildProcessCmdId = 0x0108;
        public const int StopBuildProcessCmdId = 0x0109;
        public const int SetUpTailwindMenu = 0x0110;
        public const int SetUpAndInstallTailwindCmdId = 0x0111;
        public const int SetUpTailwindCliCmdId = 0x0112;
        public const int SetUpTailwindWsCmdId = 0x0113;
        public const int SetUpTailwindGlobalCmdId = 0x0114;
        public const int SortInOpenFileCmdId = 0x0115;
        public const int SortEntireSolutionCmdId = 0x0116;
        public const int SetAsPackageConfigFileCmdId = 0x0117;
        public const int RemoveAsPackageConfigFileCmdId = 0x0118;
        public const int SetAsOutputCssFileMenu = 0x0119;
        public const int SetAsOutputCssFileCmdId = 0x0200;
        public const int tailwindLogo = 0x0001;
    }
}
